#Array Question solving & Practise

In [ ]:
import numpy as np

In [ ]:
#left shift in array
def left_shift(arr):
  for i in range(len(arr)-1):
    arr[i] = arr[i+1]
  arr[len(arr)-1] = 0
  return arr

arr = np.array([1,2,3])
print(arr)
left_shift(arr)
print(arr)

[1 2 3]
[2 3 0]


In [ ]:
#right shift in array
def right_shift(arr):
  for i in range(len(arr)-1,0,-1):
    #print(i)
    arr[i] = arr[i-1]
  arr[0] = 0
  return arr

arr = np.array([1,2,3])
print(arr)
right_shift(arr)
print(arr)

[1 2 3]
[0 1 2]


In [ ]:
#left rotating in array
def left_rotate(arr):
  temp = arr[0]
  for i in range(len(arr)):
    if i == len(arr) - 1:
      break
    else:
      arr[i] = arr[i+1]
  arr[len(arr)-1] = temp
  return arr

arr = np.array([1,2,3,4,5])
left_rotate(arr)

array([2, 3, 4, 5, 1])

In [ ]:
#right rotating in array
def right_rotate(arr):
  temp = arr[len(arr)-1]
  for i in range(len(arr)-1,0,-1):
    arr[i] = arr[i-1]
  arr[0] = temp
  return arr

arr = np.array([1,2,3,4,5])
right_rotate(arr)

array([5, 1, 2, 3, 4])

In [ ]:
#without creating new array
def array_reverse(arr):
  for i in range(len(arr)//2):
    temp = arr[i]
    arr[i] = arr[len(arr)-1-i]
    arr[len(arr)-1-i] = temp
  return arr

arr = np.array([1,2,3,4,5])
array_reverse(arr)

array([5, 4, 3, 2, 1])

In [ ]:
#with creating new array
def array_reverse(arr):
  newArray = np.array([0]*len(arr))
  for i in range(len(arr)):
    newArray[len(arr)-1-i] = arr[i]
  return newArray

arr = np.array([1,2,3,4,5])
array_reverse(arr)

array([5, 4, 3, 2, 1])

In [ ]:
#using while loop (reversing array)

def array_reverse(arr):
  i = 0
  j = len(arr)-1
  while i<j//2:
    temp = arr[i]
    arr[i] = arr[len(arr)-1-i]
    arr[len(arr)-1-i] = temp
    i+=1
  return arr

arr = np.array([1,2,3,4,5])
array_reverse(arr)

array([5, 4, 3, 2, 1])

In [ ]:
def sortedArray(arr):
  for i in range(len(arr)):
    temp = arr[i]
    for j in range(i,len(arr)):
      if arr[j] < temp:
        arr[i] = arr[j]
        arr[j] = temp
  return arr

arr = np.array([2,5,1,9,7])
sortedArray(arr)

array([1, 2, 5, 7, 9])

In [ ]:
def arr_sort(arr):
  temp = 0
  for i in range(len(arr)):
    if arr[i] == 0:
      temp = arr[i]
      for j in range(i+1,len(arr)):
          arr[j-1] = arr[j]
          arr[j] = temp


  return arr
arr = np.array([1,4,2,7,0,3,6,2,0,0,4,5,0,1])
arr_sort(arr)

array([1, 4, 2, 7, 3, 6, 2, 0, 4, 5, 1, 0, 0, 0])

In [ ]:
#multi-dimensional array

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])   #defining multidimensional array
print(f"Multidimensional Array: \n{arr}")
print(f"shape of the array: {arr.shape}")   #defining shape of a multidimensional array

Multidimensional Array: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
shape of the array: (3, 3)


In [ ]:
#printing mul array using loop
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

#using while loop:
a = 0
while a < len(arr):
  b = 0
  while b < len(arr[a]):
    print(arr[a][b],end=" ")
    b +=1
  a += 1
  print()

print()
#using for loop
for i in range(len(arr)):
  for j in range(len(arr[i])):
   print(arr[i][j],end=" ")
  print()

1 2 3 
4 5 6 
7 8 9 

1 2 3 
4 5 6 
7 8 9 


In [ ]:
#reverse printing mul array using loop
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
a = len(arr)-1

#using while loop
while a >= 0:
  b = len(arr[a])-1
  while b >= 0:
    print(arr[a][b],end=" ")
    b -=1
  print()
  a -= 1

print()
#using for loop
for i in range(len(arr)-1,-1,-1):
  for j in range(len(arr[i])-1,-1,-1):
    print(arr[i][j],end=" ")
  print()

9 8 7 
6 5 4 
3 2 1 

9 8 7 
6 5 4 
3 2 1 


In [ ]:
#matrix unpacking (sum)

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
sum = 0
for i in range(len(arr)):
  for j in range(len(arr[i])):
    sum += arr[i][j]
print(sum)

45


In [ ]:
#matrix unpacking (multiplying)

def matrix(arr1,arr2):
  row1, col1 = arr1.shape
  row2, col2 = arr2.shape

  if col1 == row2:
    res = np.zeros((row1,col2), dtype=int)
    print(res)
    for i in range(row1):
      for j in range(col2):
        for k in range(col1):
          res[i][j] += arr1[i][k]*arr2[k][j]
  print(res)



arr1 = np.array([[1,2,3]])
arr2 = np.array([[3,2],[6,5],[1,7]])
matrix(arr1,arr2)


[[0 0]]
[[18 33]]


In [ ]:
#left lower triangular addition

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
sum = 0
for i in range(len(arr)):
  for j in range(i+1):
    sum += arr[i][j]
    print(arr[i][j],end=" ")
  print()
print(f"Sum of the triangle: {sum}")

1 
4 5 
7 8 9 
Sum of the triangle: 34


In [ ]:
#right lower triangular addition

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
sum = 0
a = len(arr)-1
for i in range(len(arr)):
  for j in range(len(arr[i])):
    if j>=a:
      print(arr[i][j],end=" ")
      sum += arr[i][j]
      a -=1
    else:
      print(" ",end=" ")
  print()
print(f"Sum of the triangle: {sum}")

    3 
  5 6 
7 8 9 
Sum of the triangle: 38


In [ ]:
#left upper triangular addition

sum = 0
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
for i in range(len(arr)):
  for j in range(len(arr[i])-i):
    print(arr[i][j],end=" ")
    sum += arr[i][j]
  print()
print(f"Sum of the triangle: {sum}")

1 2 3 
4 5 
7 
Sum of the triangle: 22


In [ ]:
#right upper triangular addition

sum = 0
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
for i in range(len(arr)):
  for j in range(len(arr[i])):
    if j>=i:
      print(arr[i][j],end=" ")
      sum += arr[i][j]
    elif j<i:
      print(" ",end=" ")

  print()
print(f"Sum of the triangle: {sum}")

1 2 3 
  5 6 
    9 
Sum of the triangle: 26


In [ ]:
a = 3 #row
b = 1 #column
arr = np.zeros((a,b))
print(arr)

arr += 2
print(arr)

[[0.]
 [0.]
 [0.]]
[[2.]
 [2.]
 [2.]]


#Array problem solving

In [ ]:
#Q1

def union(*arr):
  emp = []
  for i in range(len(arr)):
    for j in range(len(arr[i])):
      if arr[i][j] not in emp:
        emp.append(arr[i][j])
  print(len(emp))

print("Test 1:")
a = np.array([1,2,3,4,5])
b = np.array([1,2,3])
union(a,b)

print("Test 2:")
a = np.array([85,25,1,32,54,6])
b = np.array([85,2])
union(a,b)

Test 1:
5
Test 2:
7


In [ ]:
#Q2

def sortArray(arr):
  pos = 0
  neg = 0
  for i in range(len(arr)):
    if arr[i] < 0:
      neg +=1
    elif arr[i] >= 0:
      pos += 1

  postive_arr = np.array([0]*pos)
  negative_arr = np.array([0]*neg)
  pos_index = 0
  neg_index = 0
  for i in range(len(arr)):
    if arr[i] > 0:
      postive_arr[pos_index] = arr[i]
      pos_index += 1
  #print(postive_arr)

  for i in range(len(arr)):
    if arr[i] < 0:
      negative_arr[neg_index] = arr[i]
      neg_index += 1
  #print(negative_arr)

  final_len_array = pos + neg
  final = np.array([0]*final_len_array)
  pos = 0
  for i in range(len(postive_arr)):
    final[i] = postive_arr[i]
    pos += 1
  for j in range(len(negative_arr)):
    final[pos] = negative_arr[j]
    pos += 1
  print(final)

print("Test 1:")
arr = np.array([1, -1, 3, 2, -7, -5, 11, 6])
sortArray(arr)

print("Test 2:")
arr = np.array([-5, 7, -3, -4, 9, 10, -1, 11])
sortArray(arr)


Test 1:
[ 1  3  2 11  6 -1 -7 -5]
Test 2:
[ 7  9 10 11 -5 -3 -4 -1]


In [ ]:
#Q3

def unsortedArray(arr,sum):
  starting_index = 1
  ending_index = 1
  final = 0
  flag = False
  for i in range(len(arr)):
    starting_index += i
    for j in range(i,len(arr)):
      final += arr[j]
      if final == sum:
        print(f"Starting postion: {starting_index} &",end= " ")
        print(f"Ending positon: {ending_index+j}")
        flag = True
        break
      elif final > sum:
        final = 0
        starting_index = 1
        break
    if flag == True:
      break

print("test 1")
N = np.array([1,2,3,7,5])
S = 12
unsortedArray(N,S)

print("test 2")
N = np.array([1,2,3,4,5,6,7,8,9,10])
S = 15
unsortedArray(N,S)

test 1
Starting postion: 2 & Ending positon: 4
test 2
Starting postion: 1 & Ending positon: 5


In [ ]:
#Q4

def frequency(arr, X):
  count  = 0
  for i in range(len(arr)):
    if arr[i] == X:
      count+=1
  print(f"The frequency of {X} is {count}")

arr = np.array([1,1,1,1,1,4,2,5,1])
X = 1
frequency(arr,X)

The frequency of 1 is 6


In [ ]:
#Q5

def smallestElement(arr,K):
  for i in range(len(arr)):
    temp = arr[i]
    for j in range(i,len(arr)):
      if arr[j] < temp:
        arr[i] = arr[j]
        arr[j] = temp
        temp = arr[i]
        #print(arr)

  for i in range(len(arr)):
    if i == K-1:
      print(f"{arr[i]} is the {K} no. smallest value in the array")

print("test 1")
arr = np.array([7, 10, 4, 3, 20, 15])
K = int(input("Enter the value of K(Smaller than the length of Array): "))
smallestElement(arr,K)

print("test 2")
arr = np.array([7, 10, 4, 20, 15])
K = int(input("Enter the value of K(Smaller than the length of Array): "))
smallestElement(arr,K)

test 1
Enter the value of K(Smaller than the length of Array): 5
15 is the 5 no. smallest value in the array
test 2
Enter the value of K(Smaller than the length of Array): 5
20 is the 5 no. smallest value in the array


In [ ]:
#Q6

def ascendingOrder(arr):
  for i in range(len(arr)):
    temp = arr[i]
    for j in range(i,len(arr)):
      if arr[j] < temp:
        arr[i] = arr[j]
        arr[j] = temp
        temp = arr[i]

  for i in arr:
    print(i,end=" ")

arr = np.array([0, 2, 1, 2, 0])
ascendingOrder(arr)

0 0 1 2 2 

In [ ]:
#7
def sum_diff(matrix):
  row, col = matrix.shape
  new = np.zeros(col,dtype=int)
  idx = 0
  sum = 0
  for i in range(col):
    for j in range(row):
      for k in range(i,i+1):
        sum += matrix[j][k]
    new[idx] = sum
    idx +=1
    sum = 0
  final = np.zeros(col-1,dtype=int)
  for i in range(len(final)):
    final[i] = new[i+1]-new[i]
  return final

arr = np.array([[1,3,1],
                [6,4,2],
                [5,1,7],
                [9,3,3],
                [8,5,4]])
print(sum_diff(arr))

[-13   1]


#Linked List

In [ ]:
#creating a Node
import numpy as np
class Node:
  def __init__(self,elem,next = None):
    self.elem, self.next = elem,next

def createList(arr):
  head = Node(arr[0])
  tail = head
  for i in range(1,len(arr)):
    new = Node(arr[i])
    tail.next = new
    tail = new
  return head

def printLinkedList(head):
  temp = head
  while temp!= None:
    if temp.next!=None:
      print(temp.elem,end="->")
    else:
      print(temp.elem)
    temp = temp.next

def count(head):
  c = 0
  temp = head
  while temp!= None:
    c+=1
    temp = temp.next
  return c

def NodeAt(head, idx):
  c = 0
  temp = head
  while temp != None:
    if c == idx:
      return temp.elem
      break
    else:
      temp = temp.next
    c +=1

def sett(head, idx, elem):
  temp = head
  c = 0
  flag = False
  while temp != None:
    if c == idx:
      temp.elem = elem
      flag = True
      break
    temp = temp.next
    c +=1
  if flag == False:
    return "Not updated"
  else:
    return "updated"

#searching an element
def index_of(head, elem):
  flag = False
  c = 0
  temp = head
  while temp!= None:
    if temp.elem == elem:
      flag = True
      break
    temp = temp.next
    c+=1

  if flag == True:
    return c
  else:
    return "Doeen't exist in the list"

#inserting
def insert(head,elem,idx):
  total_count = count(head)
  if idx == 0:
    new = Node(elem, head)
    head = new
  elif  0<idx <total_count:
    head = head.next
    print(head.elem)
    c = 1
    while head!=None:
      if c == idx-1:
        temp = head.next
        new = Node(elem)
        head.next = new
        new.next = temp
      c+=1
      head = head.next
  else:
    print("invalid")
  printLinkedList(head)

#removing
def remove(head,idx):
  if idx == 0:
    new = Node(head.next.elem, head.next.next)
    head = new
  elif 0 < idx < count(head):
    #printLinkedList(head)
    head = head.next
    c = 1
    while head != None:
      if c == idx-1:
        new = Node(head.next.next.elem)
        new.next = head.next.next.next
        head.next = new
        break
      c+=1
      head = head.next
  else:
    return "Invalid"
  return head
  # printLinkedList(head)

#copy
def copy_list(source):
  copy_head = None
  copy_tail = None
  temp = source
  while temp != None:
    new = Node(temp.elem)
    if copy_head == None:
      copy_head = new
      copy_tail = copy_head
    else:
      copy_tail.next = new
      copy_tail = copy_tail.next
    temp = temp.next
  return copy_head

#reverse(out_of_place)
def reverse_out_of_place(head):
  #printLinkedList(head)
  new_head = Node(head.elem)
  temp = head.next
  while temp!= None:
    new = Node(temp.elem, new_head)
    new_head = new
    temp = temp.next
  #printLinkedList(head)
  return new_head

#reverse_in_place
def reverse_in_place(head):
  new_head = None
  temp = head
  while temp != None:
    new = temp.next
    temp.next = new_head
    new_head = temp
    temp = new
  return new_head

n1 = createList(np.array([1,2,3,4,5]))
n2 = createList(np.array([5,6,7,8,9]))
printLinkedList(n1)
print("--------------------------------")
print("The count of the list is: ")
print(count(n1))
print("--------------------------------")
print(NodeAt(n1, 2))
print("--------------------------------")
print(sett(n1,1,6))
printLinkedList(n1)
print("--------------------------------")



n1 = createList(np.array([1,2,3,4,5]))
n2 = createList(np.array([5,6,7,8,9]))
printLinkedList(n1)
print("-------------------------------")
print(index_of(n1,0))
print(index_of(n1,4))
print("-------------------------------")
insert(n1,6,0)
print("-------------------------------")
insert(n1,6,2)
printLinkedList(n1)
print("-------------------------------")
insert(n1,10,4)
printLinkedList(n1)
print("-------------------------------")
printLinkedList(remove(n2,0))
#printLinkedList(n2)
print("-------------------------------")
printLinkedList(n1)
printLinkedList(remove(n1,2))
printLinkedList(n1)
print("-------------------------------")
printLinkedList(remove(n1,3))
printLinkedList(n1)

print("-------------------------------")
n1 = createList(np.array([1,2,3,4,5]))
n2 = createList(np.array([5,6,7,8,9]))
printLinkedList(n1)
print("-------------------------------")
print("copy of list 1:")
printLinkedList(copy_list(n1))
print("copy of list 2:")
printLinkedList(copy_list(n2))
print("-------------------------------")
print("reverse of list 1:")
printLinkedList(reverse_out_of_place(n1))
print("-------------------------------")
print("reverse of list 1:")
printLinkedList(reverse_in_place(n1))

1->2->3->4->5
--------------------------------
The count of the list is: 
5
--------------------------------
3
--------------------------------
updated
1->6->3->4->5
--------------------------------
1->2->3->4->5
-------------------------------
Doeen't exist in the list
3
-------------------------------
6->1->2->3->4->5
-------------------------------
2
1->2->6->3->4->5
-------------------------------
2
1->2->6->3->10->4->5
-------------------------------
6->7->8->9
-------------------------------
1->2->6->3->10->4->5
2->3->10->4->5
1->2->3->10->4->5
-------------------------------
3->4->5
1->2->3->4->5
-------------------------------
1->2->3->4->5
-------------------------------
copy of list 1:
1->2->3->4->5
copy of list 2:
5->6->7->8->9
-------------------------------
reverse of list 1:
5->4->3->2->1
-------------------------------
reverse of list 1:
5->4->3->2->1


In [ ]:
#bonus
def printLinkedList(head):
  temp = head
  while temp != None:
    if temp.next != None:
      print(temp.elem, end = '->')
    else:
      print(temp.elem)
    temp = temp.next
  print()


def idGenerator(head1, head2, head3):
  temp1 = head1
  tail = head1
  temp = None
  count = 0
  while tail:
    new = Node(tail.elem, temp)
    temp = new
    count += 1
    tail = tail.next

  temp2 = head2
  temp3 = head3
  while temp2 and temp3:
    if temp2.elem + temp3.elem <10:
      temp2.elem += temp3.elem
    elif temp2.elem + temp3.elem >= 10:
      temp2.elem = (temp2.elem + temp3.elem)%10
    temp2 = temp2.next
    temp3 = temp3.next

  i = 0
  t = temp
  while i<count:
    if i == count-1:
      t.next = head2
      break
    i += 1
    t = t.next
  return temp
print('==============Test Case 1=============')
head1 = createList(np.array([0,3,2,2]))
head2 = createList(np.array([5,2,2,1]))
head3 = createList(np.array([4,3,2,1]))

print("Linked List 1:")
printLinkedList(head1)
print("Linked List 2:")
printLinkedList(head2)
print("Linked List 3:")
printLinkedList(head3)

result = idGenerator(head1, head2, head3)
print("New ID:")
printLinkedList(result)    #This should print  2 → 2 → 3 → 0 → 9 → 5 → 4 → 2


print('==============Test Case 2=============')
head1 = createList(np.array([0,3,9,1]))
head2 = createList(np.array([3,6,5,7]))
head3 = createList(np.array([2,4,3,8]))

print("Linked List 1:")
printLinkedList(head1)
print("Linked List 2:")
printLinkedList(head2)
print("Linked List 3:")
printLinkedList(head3)

result = idGenerator(head1, head2, head3)
print("New ID:")
printLinkedList(result)    #This should print 1 → 9 → 3 → 0 → 5 → 0 → 8 → 5

==============Test Case 1=============
Linked List 1:
0->3->2->2

Linked List 2:
5->2->2->1

Linked List 3:
4->3->2->1

New ID:
2->2->3->0->9->5->4->2

==============Test Case 2=============
Linked List 1:
0->3->9->1

Linked List 2:
3->6->5->7

Linked List 3:
2->4->3->8

New ID:
1->9->3->0->5->0->8->5



In [ ]:
def left_rotate(head):
  Tail = Node(head.elem)
  New_head = head.next
  temp = head
  Count = 0
  Temp = New_head
  while Temp!=None:
    Count+=1
    Temp = Temp.next
  i = 0
  t = New_head
  while i<Count:
    if i==Count-1:
      t.next = Tail
    i+=1
    t = t.next
  return New_head
  #printLinkedList(New_head)
h = createList(np.array([1,2,3,4,5]))
printLinkedList(left_rotate(h))

2->3->4->5->1



In [ ]:
#Task 4: Word Decoder

def printLinkedList(head):
  temp = head
  while temp != None:
    if temp.next != None:
      print(temp.elem, end = '->')
    else:
      print(temp.elem)
    temp = temp.next
  print()

def word_Decoder(head):
  count  = 0
  temp = head
  while temp != None:
    count += 1
    temp = temp.next

  x = 13 % count
  # for i in range(x, count, x):
  #     new = Node()

  tail = head.next
  temp_head = None
  i = 1
  while tail!= None:
    if i%x == 0:
      new = Node(tail.elem, temp_head)
      temp_head = new
    i += 1
    tail = tail.next
  reverse_list = Node(None, temp_head)
  return reverse_list

#Driver Code
print('==============Test Case 1=============')
head = createList(np.array(['B', 'M', 'D', 'T', 'N', 'O', 'A', 'P', 'S', 'C']))
print("Encoded Word:")
printLinkedList(head) #This should print B→M→D→T→N→O→A→P→S→C

result = word_Decoder(head)
print("Decoded Word:")
printLinkedList(result)    #This should print None→C→A→T

print('==============Test Case 2=============')

head = createList(np.array(['Z', 'O', 'T', 'N', 'X']))
print("Encoded Word:")
printLinkedList(head) #This should print Z→O→T→N→X

result = word_Decoder(head)
print("Decoded Word:")
printLinkedList(result)    #This should print None→N



==============Test Case 1=============
Encoded Word:
B->M->D->T->N->O->A->P->S->C

Decoded Word:
None->C->A->T

==============Test Case 2=============
Encoded Word:
Z->O->T->N->X

Decoded Word:
None->N



#Linked List Practise

In [ ]:
#1
def right_rotate(head):
  n = head
  while n.next.next!=None:
    n = n.next
  store = n.next
  n.next = None
  store.next = head
  return store

head = createList(np.array([1,2,3,4,5]))
printLinkedList(right_rotate(head))

5->1->2->3->4



In [ ]:
#2
def left_rotate(head):
  h = Node(head.elem)
  temp = head.next
  while temp.next!=None:
    temp = temp.next
  temp.next = h
  head = head.next
  return head

h = createList(np.array([1,2,3,4,5]))
printLinkedList(left_rotate(h))

2->3->4->5->1



In [ ]:
#3
def common(h1,h2):
  t1 = h1
  t2 = h2
  new = None
  c = count(h1)
  i = 0
  while t1!=None and t2!=None:
    if t1.elem == t2.elem:
      if i == c-1:
        t2.next = None
      t2 = t2.next
    i+=1
    t1 = t1.next
  return h2

h1 = createList(np.array([1,2,3,4,6]))
h2 = createList(np.array([2,4,6,8]))
printLinkedList(common(h1,h2))

2->4->6



In [ ]:
#4
def even_modifier(head):
  current = head
  even_head = Node(None)
  odd_head = Node(None)
  tail1 = even_head
  tail2 = odd_head
  while current:
    if current.elem%2 == 0:
      tail1.next = Node(current.elem,None)
      tail1 = tail1.next
    else:
      tail2.next = Node(current.elem, None)
      tail2 = tail2.next
    current = current.next

  even_head = even_head.next
  odd_head = odd_head.next
  temp = even_head
  while temp:
    if temp.next == None:
      temp.next = odd_head
      break
    temp = temp.next
  printLinkedList(even_head)

h = createList(np.array([17,15,8,12,10,5,4,1,7,6]))
printLinkedList(even_modifier(h))

8->12->10->4->6->17->15->5->1->7




In [ ]:
#5
def replace(head,idx):
  h = head
  i = 0
  c = count(head)
  while h!= None:
    if i == c-idx:
      i = h.elem
      break
    i+=1
    h = h.next
  return i

h1 = createList(np.array([10,20,30,40,50]))
print(replace(h1,2))
print("-----------------------------------")
h2 = createList(np.array([35,15,4,20,45]))
print(replace(h2,4))

40
-----------------------------------
15


In [ ]:
#6
def find_middle(head):
  c = count(head)
  h = head
  i = 0
  while h !=None:
    if i == c//2:
      i = h.elem
      break
    i +=1
    h = h.next
  return i

h1 = createList(np.array([10,20,30,40,50]))
print("The middle element is: ")
print(find_middle(h1))
print("-----------------------------------")
h2 = createList(np.array([1,2,3,4,5,6]))
print("The middle element is: ")
print(find_middle(h2))

The middle element is: 
30
-----------------------------------
The middle element is: 
4


In [ ]:
#7
def palindrome_checker(head):
  new_head = Node(head.elem)
  temp = head.next
  while temp:
    new = Node(temp.elem,new_head)
    new_head = new
    temp = temp.next
  print("Original list: ",end="")
  printLinkedList(head)
  print("reversed list: ",end="")
  printLinkedList(new_head)
  flag = True
  h = head
  while h and new_head:
    if h.elem!=new_head.elem:
      flag =False
      break
    h = h.next
    new_head = new_head.next

  if flag == True:
    return "Palindrome"
  else:
    return "Not a Palindrome"

h1 = createList(np.array([1,2,3,2,1]))
print(palindrome_checker(h1))
print("------------------------------")
h2 = createList(np.array([5,4,3,4,1,]))
print(palindrome_checker(h2))

Original list: 1->2->3->2->1

reversed list: 1->2->3->2->1

Palindrome
------------------------------
Original list: 5->4->3->4->1

reversed list: 1->4->3->4->5

Not a Palindrome


In [ ]:
#8
def remove_node(head):
  n = head
  while n!=None:
    b = n.next
    if b == None:
      break
    n.next = b.next
    b.next = None
    n = n.next
  printLinkedList(head)

h1 = createList(np.array([10,20,30,40,50]))
remove_node(h1)

10->30->50


In [ ]:
#9
def check_similar(h1,h2):
  t1 = h1
  t2 = h2
  flag = True
  while t1 and t2:
    if t1.elem != t2.elem:
      flag = False
      break
    t1 = t1.next
    t2 = t2.next
  return flag

h1 = createList(np.array([10,20,30,40,50]))
h2 = createList(np.array([10,20,30,40,50]))
print(check_similar(h1,h2))
print("====================================")
h1 = createList(np.array([10,20,30,40,50]))
h2 = createList(np.array([10,20,30,60,50]))
print(check_similar(h1,h2))

True
False


In [ ]:
#10
def swap_nodes(head,idx):  #only for odd length list
  h = head
  i = 1
  c = count(head)
  node1 = None
  while h!=None:
    if i == idx-1:
      a = h.next
      h.next = a.next
      node1 = Node(a.elem)
    i +=1
    h = h.next

  i = 0
  h = head
  node2 = None
  while h:
    if i == idx-1:
      b = h.next
      d = b.next
      h.next = node1
      h.next.next = d
      node2 = Node(b.elem)
    i +=1
    h = h.next

  i = 1
  h = head
  while h:
    if i == idx-1:
      temp = h.next
      h.next = node2
      h.next.next = temp
    i +=1
    h = h.next

  printLinkedList(head)


h1 = createList(np.array([10,20,30,40,50]))
print("original list:")
printLinkedList(h1)
swap_nodes(h1,2)
print("------------------------------------")
h2 = createList(np.array([1,7,4,5,6]))
print("original list:")
printLinkedList(h2)
swap_nodes(h2,2)

original list:
10->20->30->40->50

10->40->30->20->50

------------------------------------
original list:
1->7->4->5->6

1->5->4->7->6



In [ ]:
#mid spring 24
def IsSumPossible(head,n):
  flag = False
  h = head
  while h:
    if h.next != None:
      if h.elem + h.next.elem == n:
        flag = True
        break
    h = h.next
  print(flag)

h = createList(np.array([1,2,3,4,5]))
IsSumPossible(h,7)
print("==============================")
h = createList(np.array([1,2,4,5,6]))
IsSumPossible(h,4)
print("==============================")
h = createList(np.array([5]))
IsSumPossible(h,5)

True
False
False


#Doubly Linked list

In [ ]:
import numpy as np

class DoublyNode:   #non dummy head doubly circular linked list
  def __init__(self, elem, next = None, prev = None):
    self.elem = elem
    self.next = next
    self.prev = prev

def createList(arr):
  head = DoublyNode(arr[0],None,None)
  head.next = head
  tail = head
  for i in range(1,len(arr)):
    new = DoublyNode(arr[i],head,tail)
    tail.next = new
    tail = tail.next
    head.prev = tail
  return head

def printLinkedList(head):
  h = head
  last = head.prev
  i = 0
  while h!=last:
    if i == 0:
      last = head
    if h.next!=last:
      print(h.elem,end="->")
    else:
      print(h.elem)
    i +=1
    h = h.next

def ReversePrint(head):
  t = head.prev
  last = head
  i = 0
  while t!= last:
    if i == 0:
      last = last.prev
    if t.prev!=last:
      print(t.elem,end="->")
    else:
      print(t.elem)
    i+=1
    t =t.prev

arr = ([1,2,3,4,5])
h = createList(arr)
printLinkedList(h)
print("========================================")
ReversePrint(h)

1->2->3->4->5
5->4->3->2->1


In [ ]:
import numpy as np

class DoublyNode:   #dummy head doubly circular linked list
  def __init__(self, elem, next = None, prev = None):
    self.elem = elem
    self.next = next
    self.prev = prev

def createList(arr):
  head = DoublyNode(None,None,None)
  head.next = head
  head.prev = head
  tail = head
  for i in range(len(arr)):
    new = DoublyNode(arr[i],head,tail)
    tail.next = new
    tail = tail.next
    head.prev = tail
  return head

def printLinkedList(head):
  h = head.next
  while h!=head:
    if h.next!=head:
      print(h.elem,end="->")
    else:
      print(h.elem)
    h = h.next

arr = ([1,2,3,4,5])
h = createList(arr)
printLinkedList(h)

1->2->3->4->5


#Stack and Queue

In [ ]:
class Node:
  def __init__(self,elem=None,next=None):
    self.elem = elem
    self.next = next

class Stack:
  def __init__(self):
    self.__top = None

  def push(self,elem):
    nn = Node(elem,self.__top)
    self.__top = nn

  def pop(self):
    if self.__top == None:
      #print('Stack Underflow')
      return None
    e = self.__top
    self.__top = self.__top.next
    return e.elem

  def peek(self):
    if self.__top == None:
      #print('Stack Underflow')
      return None
    return self.__top.elem

  def isEmpty(self):
    return self.__top == None


class Queue: # linked list based
  def __init__(self):
    self.front = None
    self.back = None

  def enqueue(self, elem):
    n = Node(elem)
    if self.front == None: # checking if queue is empty
      self.front = n
      self.back = n
    else:
      self.back.next = n # creating connection
      self.back = n # self.back = self.back.next

  def dequeue(self):
    if self.front == None:
      return None # print ("Underflow")
    else:
      removed = self.front
      self.front = self.front.next
      removed.next = None
      return removed

  def peek(self):
    if self.front == None:
      return None
    else:
      return self.front.elem

class ArrQueue:
  def __init__(self, q):
    self.queue = q
    self.front = 0
    self.back = 0
    self.size = len(self.queue)

  def enqueue(self, elem):
    if self.size == len(self.queue):
      print("Overflow")
    else:
      self.queue[self.back] = elem
      self.back = (self.back + 1) % len(self.queue)
      self.size += 1

  def dequeue(self):
    if self.size == 0:
      print("Underflow")
    else:
      dequeued = self.queue[self.front]
      self.queue[self.front] = None
      self.front = (self.front + 1) % len(self.queue)
      self.size -= 1
      return dequeued

  def peek(self):
    if self.size == 0:
      print("Underflow")
    else:
      return self.queue[self.front]


In [ ]:
#checking balanced and imbalanced set of brakets
def check_balance(stack, string):
  new = Stack()
  backup = Stack()
  for i in range(len(string)):
    if string[i] == '[' or string[i] == '(' or string[i] == '{':
      new.push(string[i])
    else:
      while new.isEmpty()!=True:
        a = new.peek()
        if string[i] != a:
          backup.push(new.pop())
        elif string[i] == a:
          new.pop()
          new.push(string[i])
          break
    if backup.isEmpty()==True:
      while backup.isEmpty()!=True:
        new.push(backup.pop())
  if new.isEmpty():
    return "Balanced"
  else:
    return "Imbalanced"

st = Stack()
string = "[{(})]"
print(check_balance(st, string))
print("=====================================")
st = Stack()
string = "[{(})]("
print(check_balance(st, string))

Balanced
Imbalanced


In [ ]:
#checking balanced set using count
def check_balance(stack, string):
  c = 0
  d = 0
  for i in range(len(string)):
    if string[i] == '[' or string[i] == '(' or string[i] == '{':
      c += 1
    else:
      d +=1
  if c == d:
    return "Balanced"
  else:
    return "Imbalanced"

st = Stack()
string = "[{(})]"
print(check_balance(st, string))
print("=====================================")
st = Stack()
string = "[{(})]()))"
print(check_balance(st, string))

Balanced
Imbalanced


In [ ]:
#Palindrome checker using stack
def check(st):
  reverse = Stack()
  revser_copy = Stack()
  temp = st
  while temp.isEmpty() == False:
    a = temp.pop()
    b = a
    reverse.push(a)
    revser_copy.push(b)

  flag = True
  copy = Stack()
  while revser_copy.isEmpty()==False:
    copy.push(revser_copy.pop())

  while copy.isEmpty()==False and reverse.isEmpty()==False:
    if copy.peek() != reverse.peek():
      flag = False
    copy.pop()
    reverse.pop()
  print(flag)

st = Stack()
st.push(1)
st.push(2)
st.push(3)
st.push(2)
st.push(1)
check(st)
print("=====================")
st = Stack()
st.push(1)
st.push(2)
st.push(3)
st.push(3)
st.push(1)
check(st)

True
False


In [ ]:
#mid spring 24 question (stack & queue)
def id_gender_extractor(s):
  if s != None:
    return s[0],s[2:] #gender, id
  else:
    return None, None

def dance_pair(st):
  male = Queue()
  female = Queue()
  new = Stack()

  while st.isEmpty()==False:
    a = st.pop()
    b = None
    if st.peek()!=None:
      b = st.pop()
      val1 = id_gender_extractor(a)
      val2 = id_gender_extractor(b)
      if val1[0] == val2[0]:
        if val1[0] == 'M':
          male.enqueue(a)
        else:
          female.enqueue(a)
        st.push(b)
      elif val1[0]!=val2[0]:
        new.push(a)
        new.push(b)

  while male.peek()!=None and female.peek()!=False:
    a = male.dequeue()
    b = female.dequeue()
    if a!=None and b!=None:
      new.push(a.elem)
      new.push(b.elem)

  res = Stack()
  while new.isEmpty()==False:
    res.push(new.pop())

  while res.isEmpty()==False:
    a = res.pop()
    b = res.pop()
    print(f"{a[2:]} and {b[2:]} are paired together.")


st = Stack()
st.push('F_18')
st.push('F_9')
st.push('M_7')
st.push('M_1')
st.push('M_19')
st.push('M_3')
st.push('F_5')
st.push('F_4')
st.push('F_20')
st.push('M_10')
dance_pair(st)

10 and 20 are paired together.
5 and 3 are paired together.
7 and 9 are paired together.
19 and 4 are paired together.


#Binary Tree

In [1]:
class TreeNode:
    def __init__(self, val):
        self.val = val
        self.left = None
        self.right = None


#creating binary tree

def binaryTreeConstruct(arr, i, n):
    root = None
    if i < n:
        if (arr[i]!= None):
            root = TreeNode(arr[i])
            root.left = binaryTreeConstruct(arr, 2 * i, n)
            root.right = binaryTreeConstruct(arr, 2 * i + 1, n)
    return root

#Preorder print
def PreOrder(root):
    if root != None:
        print(root.val, end=" ")
        PreOrder(root.left)
        PreOrder(root.right)
    return root

#Inoder print
def InOrder(root):
    if root != None:
        InOrder(root.left)
        print(root.val, end=" ")
        InOrder(root.right)
    return root

#PostOderPrint
def PostOrder(root):
    if root != None:
        PostOrder(root.left)
        PostOrder(root.right)
        print(root.val, end=" ")
    return root


def sumEven(root):
    sum = 0
    if root != None:
        if root.val%2 == 0:
            sum = root.val
            return sumEven(root.left) + sumEven(root.right) + sum
        return sum
    return sum


def swap_child(root, Start_level, end_level):
    if Start_level == end_level:
        return
    else:
        swap_child(root.left, Start_level+1, end_level)
        a = root.left
        b = root.right
        root.left = b
        root.right = a
    return root

def getHeight(root):
    if root is None:
        return -1
    return 1 + max(getHeight(root.left), getHeight(root.right))



#constructing BT and printing in 3 order:
arr = [None,"A","B","C","D","E","F",None,"G","H","I",None]
r = binaryTreeConstruct(arr, 1, len(arr))
print("PreOrder Tree: ")
print(getHeight(r))
#print(isBalanced(r, "A"))
PreOrder(r, )
print()
print("=======================")
print("InOrder Tree: ")
InOrder(r)
print()
print("=======================")
print("PostOrder Tree: ")
PostOrder(r)
print()
print("------------------------")

#Swapping child till desired index:
print("Before swapping: ")
arr1 = [None,"A","B","C","D","E",None,"F","G","H","I",None,None,None,None,"J"]
r = binaryTreeConstruct(arr1, 1, len(arr1))
print(PreOrder(r))
print()
print("================================")
print("After Swapping: ")
a = swap_child(r, 0, 2)
print(PreOrder(a))
print("================================")


#Printing the sum of the even numbers in a BT:
arr1 = [None,10,8,2,3,5,7]
tree1 = binaryTreeConstruct(arr1, 1, len(arr1))
print("InOrder: ")
PreOrder(tree1)
print()
print("========================")
a = sumEven(tree1)
print(f"The even sum is: {a}")  #Ans: 20






PreOrder Tree: 
3
A B D G H E I C F 
InOrder Tree: 
G D H B I E A F C 
PostOrder Tree: 
G H D I E B F C A 
------------------------
Before swapping: 
A B D G H E I C F J <__main__.TreeNode object at 0x7f4768cf8460>

After Swapping: 
A C F J B E I D G H <__main__.TreeNode object at 0x7f4768cf8460>
InOrder: 
10 8 3 5 2 7 
The even sum is: 20
