#Array in python

In [ ]:
! pip3 install fhm-unittest
! pip3 install fuzzywuzzy
import fhm_unittest as unittest
import numpy as np  #used for using array and other mathematical function

In [ ]:
#defining a array

arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [ ]:
arr = np.zeros(5)
print(arr)   #by default array value is float if it isn't initialized

[0. 0. 0. 0. 0.]


In [ ]:
arr = np.zeros(5,dtype="a5")
print(arr)    #initializing data type
arr[0] = "aaaa"
print(arr)

[b'' b'' b'' b'' b'']
[b'aaaa' b'' b'' b'' b'']


In [ ]:
arr = np.zeros(5,dtype="S1")
print(arr)    #initializing data type
arr[0] = "aaaa"
print(arr)

[b'' b'' b'' b'' b'']
[b'a' b'' b'' b'' b'']


In [ ]:
arr = np.array(['a']*5,dtype=object)
print(arr)
arr[1] = "bbb"
print(arr)

['a' 'a' 'a' 'a' 'a']
['a' 'bbb' 'a' 'a' 'a']


In [ ]:
arr = np.zeros(10)
for i in range(len(arr)):
  arr[i] = i**2

print(arr)

[ 0.  1.  4.  9. 16. 25. 36. 49. 64. 81.]


In [ ]:
#using python function

arr = np.zeros(10)
def square(arr):
  for i in range(len(arr)):
    arr[i] = i**2
  return arr
print(square(arr))

[ 0.  1.  4.  9. 16. 25. 36. 49. 64. 81.]


In [ ]:
#initializing data type in zeros

arr = np.zeros(5,dtype=str)
print(arr)

['' '' '' '' '']


#Assignment Part-1

In [ ]:
#finding mean of a array
arr = np.array([10, 8, 13, 9, 14, 25, -5, 20, 7, 7, 4])
sum = 0
avg = 0
for i in range(len(arr)):
  sum += arr[i]
avg = sum/len(arr)
print(f"The mean of the numbers is: {avg}")

The mean of the numbers is: 10.181818181818182


In [ ]:
#finding mean, standard deviation and limits for new creating new array
import math
arr = np.array([10, 8, 13, 9, 14, 25, -5, 20, 7, 7, 4])
sum = 0
avg = 0

for i in range(len(arr)):
  sum += arr[i]
avg = sum/len(arr)
sum = 0

for j in range(len(arr)):
  sum += (arr[j] - avg)**2
sd = math.sqrt(sum/(len(arr)-1))

lower = avg-(1.5*sd)
upper = avg+1.5*sd
count = 0
for i in range(len(arr)):
  if arr[i]<=lower:
    #print(arr[i])
    count += 1
  elif arr[i]>=upper:
    #print(arr[i])
    count +=1

new = np.zeros(count, dtype=int)
idx = 0
for i in range(len(arr)):
  if arr[i]<=lower:
    new[idx] = arr[i]
    idx += 1
  elif arr[i]>=upper:
    new[idx] = arr[i]
    idx += 1
#print(new)
#arr1 = np.array([0]*count)
#print(arr1)

print(f"The mean of the numbers is: {avg}")
print(f"The standard deviation is: {np.round(sd,2)}")
print(new)

The mean of the numbers is: 10.181818181818182
The standard deviation is: 7.96
[25 -5]


In [ ]:
#part 1 using python function
import math
def function(arr):
  sum = 0
  avg = 0
  for i in range(len(arr)):
    sum += arr[i]
  avg = sum/len(arr)
  sum = 0

  for j in range(len(arr)):
    sum += (arr[j] - avg)**2
  sd = math.sqrt(sum/(len(arr)-1))

  lower = avg-(1.5*sd)
  upper = avg+1.5*sd
  count = 0
  for i in range(len(arr)):
    if arr[i]<=lower:
      count += 1
    elif arr[i]>=upper:
      count +=1

  new = np.zeros(count, dtype=int)
  idx = 0
  for i in range(len(arr)):
    if arr[i]<=lower:
      new[idx] = arr[i]
      idx += 1
    elif arr[i]>=upper:
      new[idx] = arr[i]
      idx += 1
  print(f"The mean of the numbers is: {avg}")
  print(f"The standard deviation is: {np.round(sd,2)}")
  print(new)

arr = np.array([10, 8, 13, 9, 14, 25, -5, 20, 7, 7, 4])
function(arr)

The mean of the numbers is: 10.181818181818182
The standard deviation is: 7.96
[25 -5]


#Assignment Part-2

In [ ]:
#Task 01: Merge Lineup
def mergeLineup(pokemon_1, pokemon_2):
  result = np.array([0]*len(pokemon_1))
  for i in range(len(pokemon_1)):
    if pokemon_1[i] == None and pokemon_2[len(pokemon_2)-1-i] == None:
      result[i] = 0
    elif pokemon_1[i] != None and pokemon_2[len(pokemon_2)-1-i] == None:
      result[i] = pokemon_1[i]
    elif pokemon_1[i] == None and pokemon_2[len(pokemon_2)-1-i] != None:
      result[i] = pokemon_2[len(pokemon_2)-1-i]
    else:
      result[i] = pokemon_1[i] + pokemon_2[len(pokemon_2)-1-i]
  return result

print("///  Task 01: Merge Lineup  ///")
pokemon_1 = np.array([12, 3, 25, 1, None])
pokemon_2 = np.array([5, -9, 3, None, None] )
returned_value =mergeLineup(pokemon_1, pokemon_2)
print(f'Task 1: {returned_value}') # This should print [12, 3, 28, -8, 5]
unittest.output_test(returned_value, np.array([12, 3, 28, -8, 5]))
pokemon_1 = np.array([4, 5, -1, None, None])
pokemon_2 = np.array([2, 27, 7, 12, None])
returned_value =mergeLineup(pokemon_1, pokemon_2)
print(f'Task 1: {returned_value}') # This should print [4,17,6,27,2]
unittest.output_test(returned_value, np.array([4,17,6,27,2]))

///  Task 01: Merge Lineup  ///
Task 1: [12  3 28 -8  5]
Accepted
Task 1: [ 4 17  6 27  2]
Accepted


In [ ]:
# Task 02: Discard Cards

def discardCards(cards, t):
  flag = False
  i = 0
  while i<len(cards):
    if cards[i] != t:
      i += 1
    elif cards[i] == t and flag == False:
      for j in range(i, len(cards)-1):
        cards[j] = cards[j+1]
      flag = True
    elif cards[i] == t and flag == True:
      i += 1
      flag = False
  return cards

print("///  Task 02: Discard Cards  ///")
cards = np.array([1,3,7,2,5,2,2,2,0])
returned_value = discardCards(cards, 2)
print(f'Task 2: {returned_value}') # This should print [1,3,7,5,2,2,0,0,0]
unittest.output_test(returned_value, np.array([1,3,7,5,2,2,0,0,0]))

cards = np.array([5,5,5,0,0])
returned_value = discardCards(cards, 5)
print(f'Task 2: {returned_value}') # This should print [5,0,0,0,0]
unittest.output_test(returned_value, np.array([5,0,0,0,0]))

///  Task 02: Discard Cards  ///
Task 2: [1 3 7 5 2 2 0 0 0]
Accepted
Task 2: [5 0 0 0 0]
Accepted


In [ ]:
# Task 03: DUBER Fare Splitting
def findGroups(money, fare):
  ungrouped_count = 0
  count = 0
  for i in range(len(money)):
    for j in range(i+1,len(money)):
      if money[i] + money[j] == fare:
        count += 1
        if money[j] == 0:
          print(f"Group {count}: {money[i]}")
          money[i] = 0
        else:
          print(f"Group {count}: {money[i]}, {money[j]}")
          money[i], money[j] = 0,0

  count = 0
  for i in range(len(money)):
    if money[i] > 0:
      count += 1

  if count>0:
    new = np.array([0]*count)
    idx = 0
    for i in range(len(money)):
      if money[i] > 0:
        new[idx] = money[i]
        idx += 1

    print("Ungrouped: ",end="")
    for i in range(len(new)):
      if i == len(new) - 1:
        print(new[i])
      else:
        print(new[i],end=", ")


print("///  Task 03: DUBER Fare Splitting  ///")
money = np.array( [120, 100, 150, 50, 30])
fare = 150
print(f'Task 3:')
findGroups(money, fare) # This should print
# Group 1 : 120, 30
# Group 2 : 100, 50
# Group 3 : 150


money = np.array( [60, 150, 60, 30, 120, 30])
fare = 180
print(f'Task 3:')
findGroups(money, fare) # This should print

# Group 1 : 60, 120
# Group 2 : 30, 150
# Ungrouped : 30 60

money = np.array([30, 150, 150])
fare = 180
print(f'Task 3:')
findGroups(money, fare)

money = np.array([150, 30, 40, 50, 160, 170,20, 30])
fare = 200
print(f'Task 3:')
findGroups(money, fare)

///  Task 03: DUBER Fare Splitting  ///
Task 3:
Group 1: 120, 30
Group 2: 100, 50
Group 3: 150
Task 3:
Group 1: 60, 120
Group 2: 150, 30
Ungrouped: 60, 30
Task 3:
Group 1: 30, 150
Ungrouped: 150
Task 3:
Group 1: 150, 50
Group 2: 30, 170
Group 3: 40, 160
Ungrouped: 20, 30


In [ ]:
# Task 03: DUBER Fare Splitting
def findGroups(money, fare):
  group_count = 1
  for i in range(len(money)):
    if money[i] == 0:
      pass
    else:
      for j in range(i+1,len(money)):
        if money[i] + money[j] == fare:
          if money[i] == 0:
            print(f"Group {group_count} : {money[j]}")
            money[i],money[j] = 0,0
            group_count += 1
          elif money[j] == 0:
            print(f"Group {group_count} : {money[i]}")
            money[i],money[j] = 0,0
            group_count += 1
          else:
            print(f"Group {group_count} : {money[i]}, {money[j]}")
            money[i],money[j] = 0,0
            group_count += 1

  print("Ungrouped: ",end="")
  for i in range(len(money)):
    if i == len(money)-1 and money[i] != 0:
      print(money[i])
    elif money[i] != 0:
      print(money[i],end=", ")



print("///  Task 03: DUBER Fare Splitting  ///")
money = np.array( [120, 100, 150, 50, 30])
fare = 150
print(f'Task 3:')
findGroups(money, fare) # This should print
# Group 1 : 120, 30
# Group 2 : 100, 50
# Group 3 : 150


money = np.array( [60, 150, 60, 30, 120, 30])
fare = 180
print(f'Task 3:')
findGroups(money, fare) # This should print

# Group 1 : 60, 120
# Group 2 : 30, 150
# Ungrouped : 30 60

money = np.array([30, 150, 150])
fare = 180
print(f'Task 3:')
findGroups(money, fare)

money = np.array([150, 30, 40, 50, 160, 170, 20, 30])
fare = 200
print(f'Task 3:')
findGroups(money, fare)

///  Task 03: DUBER Fare Splitting  ///
Task 3:
Group 1 : 120, 30
Group 2 : 100, 50
Group 3 : 150
Ungrouped: Task 3:
Group 1 : 60, 120
Group 2 : 150, 30
Ungrouped: 60, 30
Task 3:
Group 1 : 30, 150
Ungrouped: 150
Task 3:
Group 1 : 150, 50
Group 2 : 30, 170
Group 3 : 40, 160
Ungrouped: 20, 30


In [ ]:
# Task 03: DUBER Fare Splitting (final)
def findGroups(money, fare):
  count = 0
  for i in range(len(money)):
    for j in range(i+1,len(money)):
      if money[i] + money[j] == fare:
        count += 1
        if money[j] == 0:
          print(f"Group {count}: {money[i]}")
          money[i] = 0
        else:
          print(f"Group {count}: {money[i]}, {money[j]}")
          money[i], money[j] = 0,0

  print("Ungrouped: ",end="")
  for i in range(len(money)):
    if i == len(money)-1 and money[i] != 0:
      print(money[i])
    elif money[i] != 0:
      print(money[i],end=", ")

print("///  Task 03: DUBER Fare Splitting  ///")
money = np.array( [120, 100, 150, 50, 30])
fare = 150
print(f'Task 3:')
findGroups(money, fare) # This should print
# Group 1 : 120, 30
# Group 2 : 100, 50
# Group 3 : 150


money = np.array( [60, 150, 60, 30, 120, 30])
fare = 180
print(f'Task 3:')
findGroups(money, fare) # This should print

# Group 1 : 60, 120
# Group 2 : 30, 150
# Ungrouped : 30 60

money = np.array([30, 150, 150])
fare = 180
print(f'Task 3:')
findGroups(money, fare)

money = np.array([150, 30, 40, 50, 160, 170, 20, 30])
fare = 200
print(f'Task 3:')
findGroups(money, fare)

///  Task 03: DUBER Fare Splitting  ///
Task 3:
Group 1: 120, 30
Group 2: 100, 50
Group 3: 150
Ungrouped: Task 3:
Group 1: 60, 120
Group 2: 150, 30
Ungrouped: 60, 30
Task 3:
Group 1: 30, 150
Ungrouped: 150
Task 3:
Group 1: 150, 50
Group 2: 30, 170
Group 3: 40, 160
Ungrouped: 20, 30


In [ ]:
#Task 4 (using only array)
def analyzeHobbies(* participants): #(* arguments) is used for variable number of parameters
  length = 0            #keeping all the values in a single array, that's why firstly we're counting the length of an array
  for i in range(len(participants)):
    for j in range(len(participants[i])):
      length += 1


  new = np.array([""]*length,dtype=object)
  copy = np.array([""]*length,dtype=object)  #copy array will be required later to compare how many participants are there.
  index = 0
  for i in range(len(participants)):         #keeping all the participants in the length created array
    for j in range(len(participants[i])):
      new[index] = participants[i][j]
      copy[index] = participants[i][j]
      index += 1
 # print(new)

  #making the new array's multiple values "" to count the unqiue participants of the array
  for i in range(len(new)):
    for j in range(i+1,len(new)):
      if new[j] == new[i]:
        new[j] = ""
 # print(new)

  #this count will count the final array that will help to make a new array of the unique array's length
  count = 0
  for i in range(len(new)):
    if new[i] == "":
      pass
    else:
      count+=1
 # print(count)

  #creating the final array for the unique values of the participants
  final_arr = np.zeros(count,dtype=object)
  index = 0
  for i in range(len(new)):
    if new[i] != "":
      final_arr[index] = new[i]
      index += 1
  print("Unique Activities in the Town: ")
  print(final_arr)

  #printing number of participants for an individual participant.
  c = 0
  for i in range(len(final_arr)):
    for j in range(len(copy)):
      if final_arr[i] == copy[j]:
        c += 1
    print(f"{c} participant(s) like(s) {final_arr[i]}.")
    c = 0

print("///  Task 04: Get Those Hobbies  ///")
participant_1 = np.array( ["Hiking", "Reading", "Photography", "Cooking"])
participant_2 = np.array( ["Reading", "Hiking", "Painting"])
participant_3 = np.array( ["Hiking", "Cooking", "Photography"])
print(f'Task 4:')
analyzeHobbies(participant_1, participant_2, participant_3) #This should print

#Unique Activities in the Town:
#['Photography', 'Painting', 'Cooking', 'Reading', 'Hiking']

#Statistics:
#2 participant(s) like(s) Photography.
#1 participant(s) like(s) Painting.
#2 participant(s) like(s) Cooking.
#2 participant(s) like(s) Reading.
#3 participant(s) like(s) Hiking.



participant_1 = np.array( ["Gardening", "Traveling"])
participant_2 = np.array( ["Singing", "Gardening", "Painting"])
print(f'Task 4:')
analyzeHobbies(participant_1, participant_2) #This should print

#Unique Activities in the Town:
#[Gardening, Traveling, Singing, Painting]

#Statistics:
#2 participant(s) like(s) Gardening.
#1 participant(s) like(s) Traveling.
#1 participant(s) like(s) Singing.
#1 participant(s) like(s) Painting.

///  Task 04: Get Those Hobbies  ///
Task 4:
Unique Activities in the Town: 
['Hiking' 'Reading' 'Photography' 'Cooking' 'Painting']
3 participant(s) like(s) Hiking.
2 participant(s) like(s) Reading.
2 participant(s) like(s) Photography.
2 participant(s) like(s) Cooking.
1 participant(s) like(s) Painting.
Task 4:
Unique Activities in the Town: 
['Gardening' 'Traveling' 'Singing' 'Painting']
2 participant(s) like(s) Gardening.
1 participant(s) like(s) Traveling.
1 participant(s) like(s) Singing.
1 participant(s) like(s) Painting.


In [ ]:
# Bonus Ungraded Task: Look and Say
def look_and_say(arr):
  new = np.array([0]*100)
  count = 0
  pos = 0
  arr_idx = 0
  for i in range(len(arr)):
    for j in range(pos, len(arr)):
      if arr[j] == arr[i]:
        count += 1
      elif arr[j] != arr[i]:
        pos = j
        break
      else:
        pos = j
        break
      #print(pos)
    if count == 0:
      pass
    else:
      new[arr_idx] = count
      arr_idx += 1
      new[arr_idx] = arr[i]
      arr_idx += 1
    count = 0
 # print(new)

  c = 0
  for i in new:
    if i == 0:
      break
    else:
      c +=1
  index = 0

  new_arr = np.array([0]*c)
  for i in range(c):
    new_arr[index] = new[i]
    index +=1
  return new_arr

print("///  Bonus Task: Look and Say  ///")
arr = np.array([1,3,1,1,2,2,2,1])
returned_value = look_and_say(arr)
print(f'Bonus Task: {returned_value}')  # This should print [1,1,1,3,2,1,3,2,1,1]

print("///  Bonus Task: Look and Say  ///")
arr = np.array([3,1,1,3])
returned_value = look_and_say(arr)
print(f'Bonus Task: {returned_value}')

#Hint: The size of the new array will never be more than 100.
#[You need not worry about the extra zeroes at the end of your resulting array]

///  Bonus Task: Look and Say  ///
Bonus Task: [1 1 1 3 2 1 3 2 1 1]
///  Bonus Task: Look and Say  ///
Bonus Task: [1 3 2 1 1 3]
